- src/main/java/me/totalfreedom/totalfreedommod/command/Command_opall.java
response to
https://github.com/AtlasMediaGroup/TotalFreedomMod/pull/1/files/338fc81b7f1874a79265ec46b6f308a6523f656d#r533706741
> checks if a player is OP before opping them

- src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_list.java
reordered response object and changed senioradmins & masterbuilders to senior_admins & master_builders for consistency with the bot
> reordered response object and reformat

- src/main/resources/config.yml
The current server config has these links and those ones commented out. While I do now own them not all of them I'm actively using but thought it'd be good to keep this sync'd up.
Resolves FS-12
> Update social links in line with live config

- pom.xml
Resolves FS-17 FS-19 FS-20 FS-21 FS-22
> Moved Repo's to HTTPS

- pom.xml
move away from using packs maven repo
> Mojangson update

- src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java
Hopefully this doesn't fuck up this time - last PR my Macbook was having issues with for some reason.
> Add new developers to util

- src/main/java/me/totalfreedom/totalfreedommod/admin/AdminList.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_saconfig.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_verifynoadmin.java
- src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java
Had a chat with @abhiram555 about the code and agreed to make a PR to fix players showing up as verified admin.
> Properly fix FS-33

- CONTRIBUTING.md
- LICENSE.md
- README.md
- SECURITY.md
- checkstyle.xml
- supressions.xml
This should help clear a lot of the "Security" alerts resolving FS-58
> Fix checkstyle & other formatting

- pom.xml
Given this is already in the release we should be safe I think...
> Bump version to 2021.02 Release

- pom.xml
- src/main/java/me/totalfreedom/totalfreedommod/discord/Discord.java
- src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java
The issue FS-191 has been fixed in this pr.
> Strip role/user mentions (FS-191)

- src/main/java/me/totalfreedom/totalfreedommod/command/Command_ride.java
This doesn't have an issue yet but I figured I'd fix it in this PR.
> Fixes typo in /ride 

- SECURITY.md
Updating the full security matrix.
> Update Security Matrix

- src/main/java/me/totalfreedom/totalfreedommod/command/Command_smite.java
> Switched from -c to -ci

- src/main/java/me/totalfreedom/totalfreedommod/util/FUtil.java
Name change from unsuperiordev to NotInSync.
> Name change for Fleek

- src/main/java/me/totalfreedom/totalfreedommod/LoginProcess.java
This changes how admin notes notifications are displayed to resolve an issue that prevented admin notes from displaying properly. This is my second attempt at doing it.
> Addresses FS-224 - Round 2

- .github/workflows/downstream.yml
We want to make sure anything on the main branch which is commited makes it's way down to the dev and other branches.
> Enable downward Sync from main

- pom.xml
- src/main/java/me/totalfreedom/totalfreedommod/LoginProcess.java
I screwed up and forgot to remove JSONMessage as a dependency after I removed the code that used it. This fixes that by removing both the repository and the dependency from the pom file. It wasn't used anywhere else.
> I screwed up; this fixes my mistake

- src/main/java/me/totalfreedom/totalfreedommod/command/Command_warn.java
- src/main/java/me/totalfreedom/totalfreedommod/player/FPlayer.java
- src/main/java/me/totalfreedom/totalfreedommod/punishments/PunishmentType.java
To kill two birds with one stone, I've done two fixes in this commit.
- Added WARN to the PunishmentType list.
- Fixes issue that caused quiet warns to behave improperly (e.g. the warnings wouldn't increment if quiet)
> Two fixes, one commit (FS-207)

- src/main/java/me/totalfreedom/totalfreedommod/AutoEject.java
- src/main/java/me/totalfreedom/totalfreedommod/banning/IndefiniteBan.java
- src/main/java/me/totalfreedom/totalfreedommod/blocking/BlockBlocker.java
- src/main/java/me/totalfreedom/totalfreedommod/blocking/InteractBlocker.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_cage.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_manageshop.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_notes.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_potion.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_tag.java
- src/main/java/me/totalfreedom/totalfreedommod/command/Command_toggle.java
- src/main/java/me/totalfreedom/totalfreedommod/fun/ItemFun.java
- src/main/java/me/totalfreedom/totalfreedommod/fun/Landminer.java
- src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_list.java
- src/main/java/me/totalfreedom/totalfreedommod/httpd/module/Module_players.java
Please remove the original FS-24 branch if possible.
> Code quality improvements (FS-24)

- src/main/java/me/totalfreedom/totalfreedommod/CommandSpy.java
> Admins can now see commands of everyone, regardless of rank (FS-201)

- src/main/java/me/totalfreedom/totalfreedommod/command/Command_freeze.java
> Re-words player freeze messages (FS-234)

- README.md
It's currently wrong so needed updating.
> Correct JDK Version in README

- pom.xml
Turns out jFrog is super expensive and 10GB of Bandwidth doesn't go far, this should make things a lot better :)
> Move to new ATLAS Nexus

- src/main/java/me/totalfreedom/totalfreedommod/bridge/CoreProtectBridge.java
It appears someone had an extremely big brain moment. This fixes said big brain moment.
> Critical Bugfix

- src/main/java/me/totalfreedom/totalfreedommod/command/Command_spawnmob.java
- src/main/java/me/totalfreedom/totalfreedommod/config/ConfigEntry.java
- src/main/resources/config.yml
> Makes spawnmob configurable, increases the default limit to 25 (FS-212)

- pom.xml
To align with the version running on Freedom-01 at the moment.
> Correct CoreProtect Version

- pom.xml
Merge release into development
> Release 2022.02

- pom.xml
- src/main/java/me/totalfreedom/totalfreedommod/blocking/command/CommandBlocker.java
Doing it this way so I can manually resolve the issues.
> Merge main to dev

- pom.xml
- src/main/java/me/totalfreedom/totalfreedommod/blocking/EventBlocker.java
- src/main/resources/plugin.yml
Should be about all the changes required to update TFM to 1.19.3, compiles fine, starts fine, command blocking works.
> Update to 1.19.4

- src/main/java/me/totalfreedom/totalfreedommod/MovementValidator.java
> Miscellaneous improvements to the movement validator
